// Transcript fetching via the InnerTube "player" endpoint with the ANDROID client.
// The regular WEB caption URLs require a proof-of-origin token and return empty
// bodies; the ANDROID-client caption URLs don't (same approach as youtube-transcript-api).

const WATCH_URL = 'https://www.youtube.com/watch?v=';
const PLAYER_URL = 'https://www.youtube.com/youtubei/v1/player?key=';
const ANDROID_CONTEXT = { client: { clientName: 'ANDROID', clientVersion: '20.10.38' } };
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

function decodeEntities(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)));
}

async function getInnertubeApiKey(videoId) {
  const res = await fetch(WATCH_URL + videoId, {
    headers: { 'User-Agent': UA, 'Accept-Language': 'en-GB,en;q=0.9' },
  });
  if (!res.ok) throw new Error(`YouTube watch page responded ${res.status}`);
  const html = await res.text();
  const m = html.match(/"INNERTUBE_API_KEY":\s*"([\w-]+)"/);
  if (!m) throw new Error('Could not extract InnerTube API key from watch page');
  return m[1];
}

export async function fetchTranscriptText(videoId, { languages = ['en', 'en-GB', 'en-US'] } = {}) {
  const apiKey = await getInnertubeApiKey(videoId);
  const res = await fetch(PLAYER_URL + apiKey, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'User-Agent': UA },
    body: JSON.stringify({ context: ANDROID_CONTEXT, videoId }),
  });
  if (!res.ok) throw new Error(`InnerTube player responded ${res.status}`);
  const data = await res.json();

  const status = data.playabilityStatus?.status;
  if (status && status !== 'OK') {
    throw new Error(`Video not playable: ${data.playabilityStatus?.reason || status}`);
  }

  const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  if (!tracks.length) throw new Error('Video has no captions');

  // prefer a manual track in a wanted language, then auto-generated, then anything
  const wanted = (t) => languages.some((l) => t.languageCode === l || t.languageCode.startsWith(`${l}-`));
  const track =
    tracks.find((t) => wanted(t) && t.kind !== 'asr') ||
    tracks.find(wanted) ||
    tracks.find((t) => t.kind !== 'asr') ||
    tracks[0];

  const url = track.baseUrl.replace('&fmt=srv3', '');
  const xmlRes = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!xmlRes.ok) throw new Error(`Caption track responded ${xmlRes.status}`);
  const xml = await xmlRes.text();
  if (!xml.trim()) throw new Error('Caption track returned an empty body');

  const parts = [];
  const re = /<text[^>]*>([\s\S]*?)<\/text>/g;
  let m;
  while ((m = re.exec(xml)) !== null) {
    const text = decodeEntities(m[1]).replace(/\s+/g, ' ').trim();
    if (text) parts.push(text);
  }
  const transcript = parts.join(' ');
  if (!transcript) throw new Error('Caption track contained no text');

  return {
    transcript,
    language: track.languageCode,
    autoGenerated: track.kind === 'asr',
  };
}
