import { Innertube } from 'youtubei.js';
import { fetchTranscriptText } from './transcript.js';

let innertubePromise = null;

function client() {
  if (!innertubePromise) {
    innertubePromise = Innertube.create({ lang: 'en', location: 'GB', retrieve_player: false });
  }
  return innertubePromise;
}

export function parseVideoId(input) {
  const trimmed = input.trim();
  if (/^[\w-]{11}$/.test(trimmed)) return trimmed;
  let url;
  try {
    url = new URL(trimmed);
  } catch {
    throw new Error(`Not a YouTube link or video id: ${input}`);
  }
  if (url.hostname.endsWith('youtu.be')) return url.pathname.slice(1).split('/')[0];
  const v = url.searchParams.get('v');
  if (v) return v;
  const m = url.pathname.match(/\/(shorts|live|embed)\/([\w-]{11})/);
  if (m) return m[2];
  throw new Error(`Could not extract video id from: ${input}`);
}

function textOf(value) {
  if (value == null) return '';
  if (typeof value === 'string') return value;
  if (typeof value.toString === 'function') return value.toString();
  return String(value);
}

export async function fetchTranscript(videoId) {
  const yt = await client();
  const info = await yt.getBasicInfo(videoId);
  const meta = {
    videoId,
    title: textOf(info.basic_info.title),
    channel: textOf(info.basic_info.author),
    viewCount: info.basic_info.view_count ?? null,
  };
  let transcript = '';
  let transcriptError = null;
  let language = null;
  let autoGenerated = null;
  try {
    const result = await fetchTranscriptText(videoId);
    transcript = result.transcript;
    language = result.language;
    autoGenerated = result.autoGenerated;
  } catch (e) {
    transcriptError = e.message;
  }
  return {
    ...meta,
    transcript,
    language,
    autoGenerated,
    transcriptError,
    transcriptWordCount: transcript ? transcript.split(/\s+/).length : 0,
  };
}

function parseViews(text) {
  const m = String(text).replace(/,/g, '').match(/([\d.]+)\s*([KMB])?/i);
  if (!m) return 0;
  const mult = { K: 1e3, M: 1e6, B: 1e9 }[m[2]?.toUpperCase()] ?? 1;
  return Math.round(parseFloat(m[1]) * mult);
}

function parseAgeDays(text) {
  const m = String(text).match(/(\d+)\s*(minute|hour|day|week|month|year)/i);
  if (!m) return 99999;
  const per = { minute: 1 / 1440, hour: 1 / 24, day: 1, week: 7, month: 30, year: 365 }[
    m[2].toLowerCase()
  ];
  return Math.round(Number(m[1]) * per);
}

// deliberately rough — the client asked for a helper, not perfect detection
const UK_RE = /\buk\b|british|britain|england|scotland|wales|🇬🇧/i;

export async function searchVideos(query, { max = 20 } = {}) {
  const yt = await client();
  const res = await yt.search(query, { type: 'video' });
  return (res.videos ?? [])
    .slice(0, max)
    .map((v) => {
      const title = textOf(v.title);
      const channel = textOf(v.author?.name);
      const views = textOf(v.short_view_count?.text ?? v.short_view_count ?? '');
      const published = textOf(v.published?.text ?? v.published ?? '');
      return {
        videoId: v.video_id ?? v.id,
        title,
        channel,
        views,
        published,
        duration: textOf(v.duration?.text ?? ''),
        viewsNum: parseViews(views),
        ageDays: parseAgeDays(published),
        looksUk: UK_RE.test(`${title} ${channel}`),
      };
    })
    .filter((v) => v.videoId)
    .sort((a, b) => b.viewsNum - a.viewsNum);
}

export async function fetchComments(videoId, { maxComments = 5000, includeReplies = true } = {}) {
  const yt = await client();
  const comments = [];
  let capped = false;

  function push(view) {
    if (!view) return;
    comments.push({
      author: textOf(view.author?.name),
      text: textOf(view.content),
      likes: textOf(view.like_count) || '0',
      published: textOf(view.published_time),
    });
  }

  let section = await yt.getComments(videoId, 'TOP_COMMENTS');
  while (true) {
    for (const thread of section.contents ?? []) {
      push(thread.comment);
      if (includeReplies && thread.replies) {
        for (const reply of thread.replies ?? []) push(reply.comment ?? reply);
      }
      if (comments.length >= maxComments) {
        capped = true;
        break;
      }
    }
    if (capped || !section.has_continuation) break;
    try {
      section = await section.getContinuation();
    } catch {
      break;
    }
  }

  return { videoId, comments, commentCount: comments.length, capped };
}
