import { Innertube } from 'youtubei.js';
import { fetchTranscriptText } from './transcript.js';

let innertubePromise = null;

function client() {
  if (!innertubePromise) {
    innertubePromise = Innertube.create({ lang: 'en', location: 'GB', retrieve_player: false });
  }
  return innertubePromise;
}

export function parseVideoId(input) {
  const trimmed = input.trim();
  if (/^[\w-]{11}$/.test(trimmed)) return trimmed;
  let url;
  try {
    url = new URL(trimmed);
  } catch {
    throw new Error(`Not a YouTube link or video id: ${input}`);
  }
  if (url.hostname.endsWith('youtu.be')) return url.pathname.slice(1).split('/')[0];
  const v = url.searchParams.get('v');
  if (v) return v;
  const m = url.pathname.match(/\/(shorts|live|embed)\/([\w-]{11})/);
  if (m) return m[2];
  throw new Error(`Could not extract video id from: ${input}`);
}

function textOf(value) {
  if (value == null) return '';
  if (typeof value === 'string') return value;
  if (typeof value.toString === 'function') return value.toString();
  return String(value);
}

export async function fetchTranscript(videoId) {
  const yt = await client();
  const info = await yt.getBasicInfo(videoId);
  const meta = {
    videoId,
    title: textOf(info.basic_info.title),
    channel: textOf(info.basic_info.author),
    viewCount: info.basic_info.view_count ?? null,
  };
  let transcript = '';
  let transcriptError = null;
  let language = null;
  let autoGenerated = null;
  try {
    const result = await fetchTranscriptText(videoId);
    transcript = result.transcript;
    language = result.language;
    autoGenerated = result.autoGenerated;
  } catch (e) {
    transcriptError = e.message;
  }
  return {
    ...meta,
    transcript,
    language,
    autoGenerated,
    transcriptError,
    transcriptWordCount: transcript ? transcript.split(/\s+/).length : 0,
  };
}

export async function searchVideos(query, { max = 10 } = {}) {
  const yt = await client();
  const res = await yt.search(query, { type: 'video' });
  return (res.videos ?? [])
    .slice(0, max)
    .map((v) => ({
      videoId: v.video_id ?? v.id,
      title: textOf(v.title),
      channel: textOf(v.author?.name),
      views: textOf(v.short_view_count?.text ?? v.short_view_count ?? ''),
      published: textOf(v.published?.text ?? v.published ?? ''),
      duration: textOf(v.duration?.text ?? ''),
    }))
    .filter((v) => v.videoId);
}

export async function fetchComments(videoId, { maxComments = 5000, includeReplies = true } = {}) {
  const yt = await client();
  const comments = [];
  let capped = false;

  function push(view) {
    if (!view) return;
    comments.push({
      author: textOf(view.author?.name),
      text: textOf(view.content),
      likes: textOf(view.like_count) || '0',
      published: textOf(view.published_time),
    });
  }

  let section = await yt.getComments(videoId, 'TOP_COMMENTS');
  while (true) {
    for (const thread of section.contents ?? []) {
      push(thread.comment);
      if (includeReplies && thread.replies) {
        for (const reply of thread.replies ?? []) push(reply.comment ?? reply);
      }
      if (comments.length >= maxComments) {
        capped = true;
        break;
      }
    }
    if (capped || !section.has_continuation) break;
    try {
      section = await section.getContinuation();
    } catch {
      break;
    }
  }

  return { videoId, comments, commentCount: comments.length, capped };
}
